version: "3.9"

# For local development only
services:
  web:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    env_file: ./client/.env.development
    volumes:
        - "./client/:/app"
        - "/app/node_modules"
    ports:
      - 3333:3000
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - "./server/:/rest"
      - "/rest/node_modules"
    ports:
      - 5000:3000