apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-updater
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-updater
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: secret-updater
subjects:
- kind: ServiceAccount
  name: secret-updater
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-updater
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  schedule: "@monthly"
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          containers:
          - image: alexohneander/kube-certbot:latest
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 80
            env:
            - name: DOMAINS
              value: YOURDOMAINS
            - name: EMAIL
              value: YOUREMAIL
            - name: NAMESPACE
              value: default
            - name: SECRET
              value: letsencrypt-certs
          restartPolicy: Never
          serviceAccountName: secret-updater
---
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
spec:
  selector:
    app: letsencrypt
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: TLS