# Only for local development to emulate pipeline
FROM node:lts-alpine

WORKDIR /rest

RUN apk add g++ make py3-pip

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 3000

CMD [ "node", "dist/main" ]